source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BSTableViewReorder_Example', :exclusive => true do
  pod "BSTableViewReorder", :path => "../"
end

target 'BSTableViewReorder_Tests', :exclusive => true do
  pod "BSTableViewReorder", :path => "../"

  
end
